# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3323bff51ca2bd27fd206b74f647346b6df3d6dde76b82359fb42f423c329e4971b4c9b0e2d5cbd0ba4187d96af2f735a1ee1c6a9743678f5f038cc895106d6f

test:
  secret_key_base: 385f79a701936fbd2b58566d336a3ed2e1855b62f02c110ceaf4d3b23da5b816a3fb3019c6cf2871064e84804bbf7bc091c712a98eaad36e08809c89a55390b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
